default: &default
  adapter: postgresql
  encoding: unicode
  username: myapp
  password: password1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_clone_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # database: twitter_clone_production
  # username: twitter_clone
  # password: <%= ENV["TWITTER_CLONE_DATABASE_PASSWORD"] %>